spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hmcts_dev_db
    username: hmcts_user
    password: hmcts_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
